AppDaddy-Software-Solutions-Inc/framework-markup-language

lib/system.dart
lib/widgets/button/button_view.dart

This fixes the issue when sizing a button that it is larger than its specified size when compared to other widgets

Button sizing conformity

---

lib/datasources/http/http.dart
lib/datasources/http/model.dart
lib/datasources/http/patch/model.dart
lib/postmaster/postmaster.dart

- Added PATCH HTTP Request
- Added required BODY to PATCH, POST and PUT (although posts/puts can be an empty string)
- Removed BODY from DELETE
Based off the specs from https://httpwg.org/specs/rfc9110.html#method.definitions

added patch and enforced required http bodys

---

lib/datasources/gps/gps.mobile.dart
lib/datasources/gps/gps.web.dart
lib/widgets/map/map_view.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.yaml

@JeffOlajos take a look at these changes

gps web fix

---

lib/datasources/sse/sse.mobile.dart
lib/store/store_model.dart
lib/widgets/span/span_model.dart

default to https from app store

---

lib/widgets/grid/grid_view.dart
lib/widgets/list/list_view.dart
lib/widgets/table/table_view.dart

scrollto for grid/table/list

---

lib/widgets/popover/popover_view.dart
lib/widgets/radio/radio_view.dart
lib/widgets/slider/slider_view.dart

- fix popover text and surface on dark themes
- fixed slider enabled=false
- fixed radio widget crash when enabled=false without color set

minor widget fixes

---

lib/datasources/socket/socket_model.dart
lib/system.dart
lib/widgets/box/box_view.dart
lib/widgets/framework/framework_view.dart
lib/widgets/select/select_view.dart
pubspec.yaml

The clipping should be fixed by https://github.com/flutter/flutter/issues/110628

Small bug fixes found in testing

---

lib/navigation/manager.dart
lib/widgets/widget/widget_model.dart

- small fix for <BODY> tags showing up as non-widgets, which is correct but we often use a body tag within datasources

fix for back until

---

lib/datasources/nfc/nfc_model.dart

Fixed the method not getting set.

NFC method get set fix

---

lib/widgets/select/select_model.dart

Works for both datasource and hardcoded options the same now.

Fix for SELECT hardcoded value

---

lib/widgets/select/select_view.dart

previous changes removed the case insensitivity, adding it back for easier matching

Typeahead Select pattern match with case insensitivity

---

lib/event/handler.dart
lib/widgets/tabview/tab_model.dart
lib/widgets/tabview/tab_view.dart
lib/widgets/text/text_view.dart

- fixed the material3 padding that was altered
- improved the view styling
- added a close other tabs button

tabview fixes

---

lib/system.dart
lib/widgets/text/text_view.dart

text should always be constrained horizontally and unconstrained vertically.

Fix for text not handling its own overflow

---

lib/system.dart
lib/widgets/table/header/cell/table_header_cell_view.dart
lib/widgets/table/header/table_header_view.dart

- fixed header sizing from model
- removed offset padding
- fixed sorting icon display order

table header sort buttons

---

lib/widgets/camera/camera_view.dart

Added more error messages
Added exception catching
Added a safer re-initialization
Added null safe controller checks

Improve error handing on Camera

---

assets/applications/fmlpad/fmlpad.xml
lib/eval/eval.dart
lib/widgets/widget/decorated_widget_model.dart

Modified Color to check if Eval.
FmlPad Updates

Added Join Function to Join "n" Strings in an Eval().

---

lib/widgets/table/header/cell/table_header_cell_view.dart

- Adds padding to the left and right to keep the table header content easily readable
- Defaulted valign to center on the table headers.

table header padding and alignment

---

pull_request_template.md

I have added a PR template that must be submitted with each PR. This will help both the reviewer and the requestor ensure all pieces are met.

Pull Request Template, must be used on all PR's

---

lib/widgets/text/text_view.dart

Emojii fix. Value parse was defeated on earlier TextView optimatization.

---

lib/sound/sound.dart
lib/splash/splash.dart

Adds Error handling for Splash Images and Sound
- Adds Error handling for Splash Images and Sound
- n/a
- [event] sound()
- [initialization process] splash screen
- Invalid resources either from links or local assets
```xml
<BTN type="elevated" onclick="sound('nonexistantfile.mp3')">
<BOX center="true" width="250" height="40">
<TEXT label="sound('beep.mp3')" size="18" />
</BOX>
</BTN>
```
n/a
Sound example in fmlpad

Error handling for Splash Images and Sound

---

lib/widgets/video/video_view_selector_vm.dart
lib/widgets/video/video_view_vlc.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
pubspec.yaml
windows/flutter/generated_plugins.cmake

Remove vlc player as it violates their copy-left license.
- Remove the dart_vlc library
- Video element will not work and will need to be re-written
- VIDEO
-

Remove vlc library

---

lib/system.dart
lib/widgets/video/video_model.dart
lib/widgets/video/video_view.dart
lib/widgets/video/video_view_selector_web.dart
lib/widgets/widget/widget_model.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.yaml

- Commented out the video player wiring that was remaining until a suitable package alternative is implemented.
- This allows us to build after the video player removal.
-VIDEO
- Successful build for all platforms.
-

Removed Video Player Remnants

---

pubspec.yaml

Fix pubspec for release
- remove caret on dep override for linux build
- fix version
- forces firebase-core 4.5.1
- n/a
- b/a
- n/a
n/a

Fix pubspec for release

---

ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
ios/Runner/Info.plist

ios fixes for v1.3.0 and iOS SDK 16
- ios fixes for v1.3.0 and iOS SDK 16

ios fixes for v1.3.0 and iOS SDK 16

---

assets/applications/fmlpad/fmlpad.xml

Fixed the flip side of the card mirroring the button crrectly
- Had the face be the opposite of the button, made the root pad.fml.dev
- N/A
- N/A
- Ran fmlpad in windows, ensured the button toggled the correct way and the examples were displayed.
N/A
- N/A

Fixed root and card side

---

lib/datasources/base/model.dart
lib/datasources/iDataSource.dart
lib/datasources/transforms/filter.dart
lib/datasources/transforms/transform_model.dart
lib/event/handler.dart
lib/observable/observable.dart
lib/observable/observables/list.dart
lib/system.dart
lib/widgets/widget/widget_model.dart
macos/Flutter/GeneratedPluginRegistrant.swift

Fix filter by allowing for both eval, and bindings to be used in the `filter` as well as the `enabled`
- Filter now has the ability to use bindings and evals
- Filter now has an enabled property
- Filter can now be dynamic with bindings within the `filter` eval and will update when the bindings change
- Datasources with Filters
- Created a test case for Filter as it was missing and applied various filters that contained bindings that changed.
<details>
<summary>See example</summary>
```xml
<FML>  
<DATA id="People" root="SET.ROW">
<VALUE>
<![CDATA[
<SET>
<ROW>
<NAME>Avery Alberton</NAME>
<COUNTRY>United States</COUNTRY>
<CITY>Chicago</CITY>
</ROW>
<ROW>
<NAME>Ben Bordeau</NAME>
<COUNTRY>Canada</COUNTRY> …
```

Filter fixes

---

lib/widgets/camera/camera_view.dart

Fix for tapping the screen during camera interface
- Add try catch around platform specific implementations on screen tap for exposure point and focus point
- none
- Camera
- Camera doesn't cause a crash on web/desktop when tapping the screen
<details>
```xml
<FML title="CAMERA (example1)" orinentation="lanscape">
<POST id="ds1" url="https://fml.dev/api/demo/user/image" onsuccess="alert('success','{ds1.statusmessage}')" onfail="alert('error','{ds1.statusmessage}')">
<BODY>
<![CDATA[ <User> <email>test@imageupload.com</email> <picture>{wc1.data.file}</picture> </User> ]]>
</BODY>
</POST>
<VAR id="istaking" …
```

error handling for camera screen tap

---

lib/widgets/form/form_model.dart

form was being defined twice
FORM was not posting and displaying the busy spinner endlessly.
- form was defined twice, resulting in the outer definition to return null.
- Changed the definition to a reference, bug was introduced in commit #6fdda5f
- n/a
- FORM and its related events save() complete() and validate()
- Tested form on web where the bug was reported, tested with configurations of onsuccess and onfail.
<details>
```xml
<POST id="post" onsuccess="toast('Apex Check Saved', '5');back();" onfail="alert('warning')" root="Row">
<HEADER key="Content-Type" value="application/xml"/>
<URL> …
```

Form posting fix

---

lib/datasources/stash/stash_model.dart
lib/hive/stash.dart
lib/widgets/widget/widget_model.dart

- Made Stash a datasource
- STASH is now a datasource (similar to LOG)
- Can now use <STASH> to access the stash datasource of "key" and "value" fields
- n/a
- I added values to the stash then used the template below to see if they came back from the datasource
<details>
```xml
<STASH id="STASH" autoexecute="true" />
<SCROLLER>
<ROW valign="end">
<TEXT style="h3" color="{THEME.primary}" >Stash</TEXT>
<PAD left="12" bottom="6">
<TEXT size="18" color="{THEME.primary}">({SYSTEM.domain})</TEXT>
</PAD>
</ROW>
<PAD top="30" />
<BOX height="={SYSTEM.screenheight} - 250">
<TABLE id="stashtabl" …
```

Made Stash a datasource

---

lib/widgets/pager/pager_view.dart

- fixed a bug where current page wouldn't update when scrolling or dragging to change the page
- currentPage will now be reflected by anything that changes the page, previously only the page() event and dotindicator would update this binding
- Pager's currentPage now updates properly from touch/scroll events
- currentPage will now update when a user scrolls or drags to a new page
- Pager
- Windows/Web/Android I added a pager with bindings to ensure current page was reflected when scrolling/dragging
<details>
```xml
<VAR id="currpage" value="{p1.currentpage}" …
```

Improve Pager's currentPage bindable

---

lib/application/application_model.dart

stash values removed when null to reduce observables
- n/a
- n/a
- STASH
- Tested removing values from the stash by setting the value of a stash key to null.
<details>
```xml
stash({key}, null);
```
</details>  

stash values removed when null to reduce observables

---

lib/widgets/list/item/list_item_view.dart

list item view color fix
- n/a
- n/a
- LIST ITEM
- made a list item

list item view color fix

---

lib/helper/time.dart
pubspec.yaml

Added Time Helper Class
- Added a Time Helper 
- n/a
- n/a
- n/a

Added Time helper Class

---

pubspec.yaml

- Removed unused packages
- Added in lints that is hanging on another branch.
- Ran on web and desktop

Pubspec cleanup

---

lib/helper/string.dart
lib/token/token.dart
lib/widgets/chart/chart_view.dart
lib/widgets/constraints/constraint_model.dart
lib/widgets/framework/framework_view.dart
lib/widgets/input/input_view.dart
lib/widgets/layout/layout_model.dart
lib/widgets/menu/menu_view.dart
lib/widgets/overlay/overlay_view.dart
lib/widgets/pager/pager_view.dart
lib/widgets/scribble/scribble_view.dart
lib/widgets/select/select_view.dart
lib/widgets/stack/stack_model.dart
lib/widgets/video/video_view.dart
lib/widgets/viewable/viewable_widget_model.dart
lib/widgets/widget/widget_model.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

Sibling awareness

---

lib/crypto/crypto.dart
lib/widgets/animation/animation_view.dart
lib/widgets/constraints/constraint_model.dart
lib/widgets/grid/item/grid_item_view.dart
lib/widgets/input/input_view.dart
lib/widgets/table/table_view.dart
lib/widgets/treeview/node/tree_node_view.dart
lib/widgets/video/video_view.dart
lib/widgets/viewable/viewable_widget_model.dart
pubspec.yaml
windows/flutter/generated_plugins.cmake

- 
- 
- 
- 
<details>
```xml
```
</details>  

Lint Fixes

---

lib/system.dart
lib/widgets/box/box_model.dart
lib/widgets/chart/chart_model.dart
lib/widgets/column/column_model.dart
lib/widgets/constraints/constraint_model.dart
lib/widgets/framework/framework_view.dart
lib/widgets/grid/grid_model.dart
lib/widgets/layout/layout_model.dart
lib/widgets/list/list_model.dart
lib/widgets/map/map_model.dart
lib/widgets/overlay/overlay_view.dart
lib/widgets/row/row_model.dart
lib/widgets/scroller/scroller_model.dart
lib/widgets/stack/stack_model.dart
lib/widgets/table/table_model.dart
lib/widgets/tabview/tab_model.dart
lib/widgets/viewable/viewable_widget_model.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

Layout fixes4

---

lib/widgets/widget/widget_model.dart

small typo in widget_model.dart
- 
- 
- 
- 
<details>
```xml
```
</details>  

small typo in widget_model.dart

---

lib/widgets/box/box_mixin.dart
lib/widgets/box/box_model.dart
lib/widgets/box/box_view.dart
lib/widgets/box/flex_renderer.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

Layout Merge Fixes

---

lib/platform/platform.web.dart

fix for platform-web merge mistake

fix for platform-web merge mistake

---

lib/datasources/base/model.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

Datasource DATA _setter() fixes

---

lib/widgets/busy/busy_view.dart
macos/Flutter/GeneratedPluginRegistrant.swift
windows/flutter/generated_plugins.cmake

- 
- 
- 
- 
<details>
```xml
```
</details>  

BusyWidget in store not displaying on app/remove App

---

lib/widgets/table/row/cell/table_row_cell_model.dart
lib/widgets/table/row/cell/table_row_cell_view.dart

- Selectedcolor and selectedbordercolor working
- TABLE and children

Selectedcolor and selectedbordercolor working

---

lib/store/store_view.dart
lib/system.dart
lib/widgets/chart/chart_view.dart

- Fix chart bug with all null data values causing infinity with intervals
- also matched store button to menu buttons
- n/a
- n/a
- Chart/Store
- web/win desktop
<details>
```xml
<FML>
<BOX>
<BOX height="500">
<CHART id="examplechart" showlegend="true" legendsize="20">
<XAXIS type="String" title="Month" />
<YAXIS type="numeric" title="Amount" truncate="true" interval="2" />
<LABEL y1="6" y2="10" label="Safezone" anchor="end" color="#663FF955"/>
<LABEL y1="4" y2="6" label="Caution" anchor="end" color="#66EF9000"/>
<LABEL y1="10" y2="12" label="Caution" anchor="end" …
```

fixed chart bug

---

lib/widgets/framework/framework_view.dart
lib/widgets/list/list_view.dart
lib/widgets/pager/pager_view.dart

bug fix for pager build during build
- n/a
- n/a
- Pager
- windows/web pager with binding to `currentpage`

bug fix for pager build during build

---

ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.yaml

ios updates for 2.0.0

---

lib/datasources/base/model.dart
lib/datasources/transforms/calc.dart
lib/datasources/transforms/distinct.dart
macos/Flutter/GeneratedPluginRegistrant.swift

Added total to calc to determine distinct totals and add to a field
- added operation = total to CALC, sorted DISTINCT mapping incorrectly.
- CALC total and DISTINCT
- Tested on a dataset
<details>
```xml
<GET id="trackerdata" url="resources/planedata.json">
<CALC id="f2" target="dayOfWeek" operation="eval" source="toDate('{data.firstSeen}000', '', 'EEEE')"/>
<CALC target="arrivalCount" source="dayOfWeek" operation="total"/>
<DISTINCT field="dayOfWeek"/>
</GET>
```
</details>  
Thank you for your effort to improve FML! If you have any other comments please leave them as a separate …

Fixed DISTINCT, added total to calc

---

lib/data/data.dart
lib/helper/xml.dart
lib/widgets/chart/axis/chart_axis_model.dart
lib/widgets/chart/chart_model.dart
macos/Flutter/GeneratedPluginRegistrant.swift

ChartAxis and Data Fixes for non String JSON

fix chartaxis initialization

---

lib/event/event.dart
lib/event/handler.dart
lib/widgets/pager/pager_model.dart
lib/widgets/pager/pager_view.dart

Changed the pager to take id referenced events instead of global events
- Pager now takes an id referenced 
- instead of using the global `page(1)` event now pagers must be referenced by id ie: `pagerid.page(1)`
- Pager/Event
- I built a test pager to test each event on windows desktop
<details>
```xml
<FML>
<BOX color="white" />
<PAGER id="p1" pager="true">
<PAGE>
<BOX layout="column" valign="center" halign="center" color="#E2ACC6,#FDCC98">
<TEXT style="h1">
Page 1
</TEXT> 
</BOX>
</PAGE>
<PAGE>
<BOX layout="column" valign="center" halign="center" color="#FDCC98,#FC6C81"> …
```

Pager event update

---

lib/widgets/chart/axis/chart_axis_model.dart
lib/widgets/chart/chart_view.dart

- fix pie chart assignment by chart type or series type
- n/a
- chart
- built pie charts

pie chart assignment fix

---

lib/datasources/transforms/distinct.dart
lib/widgets/box/box_model.dart
lib/widgets/box/box_view.dart
lib/widgets/modal/modal_model.dart
lib/widgets/modal/modal_view.dart
macos/Flutter/GeneratedPluginRegistrant.swift

Look and Feel of Modal
Modal Header now more window like
Modal
- 
<details>
```xml
```
</details>  

Modal View Mods

---

lib/widgets/framework/framework_view.dart
lib/widgets/list/item/list_item_model.dart

- Removed setWidth() and setHeight on Framework Body
- Should see no ill effects. Framework in Splitter or Modal should exp[and to fill.
- Framework, SplitView and Modal
- 

Removed setWidth() and setHeight on Framework Body

---

lib/widgets/popover/item/popover_item_model.dart
lib/widgets/popover/popover_model.dart
lib/widgets/popover/popover_view.dart
lib/widgets/widget/widget_model.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.yaml

Added datasource to Popover to dynamically populate PopoverMenuItems 
- Also updated some packages
- Popover's item children can now be built from a datasource 
- n/a
- Popover
- PopoverItem
- web/windows with static datasources
<details>
```xml
<POPOVER icon="code" label="Snippets" data="dbWidgets">
<ITEM label="&lt;{data.title} /&gt;" onclick="copy({data.value})" />
</POPOVER>
```
</details>  

Added datasource to Popover to dynamically populate PopoverMenuItems 

---

lib/widgets/animation/animation_child/flip/flip_card_view.dart
lib/widgets/animation/animation_child/slide/slide_transition_view.dart
lib/widgets/animation/animation_child/transform/transform_model.dart
lib/widgets/animation/animation_child/transform/transform_view.dart
lib/widgets/form/form_model.dart
macos/Flutter/GeneratedPluginRegistrant.swift

Elementat throws index error when not supplied.
- Checked length when elementat is used.
- no bug when not supplying all values needed.
- TRANSFORM, SLIDE, FLIP
<details>
```xml
See animation-example1 on PAD
```
</details>  

Transform elementat fix

---

lib/widgets/box/box_mixin.dart
lib/widgets/constraints/constraint_model.dart
lib/widgets/framework/framework_view.dart
lib/widgets/splitview/split_view.dart
lib/widgets/widget/widget_model.dart

- SplitView wasn't sizing correctly
- No change
- SplitView
- As per layout test below
<SPLITVIEW id="split1" ratio=".70" direction="horizontal" widthh="50%" height="300">
<VIEW id="view1" height="10%" color="red" border="all" borderwidth="5" bordercolor="blue700">
</VIEW>
<VIEW id="view2" center="true" color="pink" border="all" borderwidth="5" bordercolor="green700">
<ICON icon="face" color="{THEME.primary}"/>
</VIEW>
</SPLITVIEW>

Splitview fix

---

lib/system.dart
lib/widgets/map/map_view.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.yaml

update packages pre 2.0

---

lib/helper/xml.dart
lib/widgets/box/box_mixin.dart
lib/widgets/box/box_model.dart
lib/widgets/box/box_view.dart
lib/widgets/box/flex_renderer.dart
lib/widgets/box/stack_renderer.dart
lib/widgets/box/wrap_renderer.dart
lib/widgets/button/button_model.dart
lib/widgets/button/button_view.dart
lib/widgets/card/card_model.dart
lib/widgets/modal/modal_model.dart
lib/widgets/pager/pager_model.dart
lib/widgets/pager/pager_view.dart
lib/widgets/splitview/split_model.dart
lib/widgets/splitview/split_view.dart
lib/widgets/stack/stack_model.dart
lib/widgets/viewable/viewable_widget_model.dart
lib/widgets/widget/widget_model.dart

- Button now inherits from Box
- Button can have layout, sizing
- Button
- Layout Test
<FML layout="row">
<BUTTON flex="1" type="elevated" layout="col" radius="6" color="red" expand="false" onclick="open('https://pad.fml.dev')">
<TXT size="26" color="white" lineheight="1.5" value="I'm not interested in downloading anything yet, but I would like to try out the online FMLPad editor." />
<PAD top="10" />
<BOX expand="false" radius="50" color="blur">
<ICON icon="expand_more" color="white" size="64" />
</BOX>
</BUTTON>
<PADDING all="20" />
<BUTTON flex="2" type="elevated" radius="6" layout="col" color="green" expand="false" …

Button inherit fixes

---

lib/widgets/button/button_model.dart
lib/widgets/modal/modal_model.dart
lib/widgets/table/row/cell/table_row_cell_view.dart

Fixed the button defaults now that it is box based.
- Button now is treated like a box and carries most of its attributes
- n/a
- Button
- Tested out application on test

button defaults

---

lib/eval/text_parser.dart
lib/widgets/span/span_model.dart
lib/widgets/span/span_view.dart
lib/widgets/text/text_model.dart
lib/widgets/text/text_view.dart
macos/Flutter/GeneratedPluginRegistrant.swift

- Added a attribute called "selectable" on text to allow users to select it.
- Fixed the parsing around markdown to allow for characters post syntax
- TEXT and SPAN can now have a `selectable=true` to enable text selection
- Markdown syntax bug fixes
- n/a
- <TEXT> / text_parser
- I tested each configuration of the new markdown regexs, here is most of them
<details>
```xml
<COL>
<TEXT value="a string to show ```code example``` text" pad="5" />
<TEXT value="a string to show ```code example```." pad="5" />
<TEXT value="a string to show ```code …

Add selectable text and fixed markdown regex

---

lib/widgets/button/button_model.dart

- fixed text button color and enabled/disabled
- cleaned up label deserialize
- centered buttons children by default
- n/a
- n/a, trying to retain old functionality
- Button
- fmlpad example
<details>
```xml
<FML title="BUTTON (example1)" linkable="true">
<BOX center="true">
<PAD all="20" />
<BUTTON label="Text Button" onclick="toast('Clicked!')" radius="36" color="orange" />
<PAD all="20" />
<BUTTON id="elevatedbtn" type="elevated" onclick="elevatedbtn.color.set('random');txt.color.set('random');" radius="36" color="grey">
<TEXT id="txt" …
```

Button fixed for fmlpad

---

lib/helper/string.dart
lib/system.dart
lib/widgets/checkbox/checkbox_model.dart
lib/widgets/googlemap/map_model.dart
lib/widgets/grid/grid_model.dart
lib/widgets/grid/grid_view.dart
lib/widgets/list/item/list_item_model.dart
lib/widgets/list/item/list_item_view.dart
lib/widgets/list/list_model.dart
lib/widgets/map/map_model.dart
lib/widgets/map/map_view.dart
lib/widgets/map/marker/map_marker_model.dart
lib/widgets/menu/menu_model.dart
lib/widgets/pager/pager_model.dart
lib/widgets/popover/popover_model.dart
lib/widgets/radio/radio_model.dart
lib/widgets/select/select_model.dart
lib/widgets/table/table_model.dart
lib/widgets/typeahead/typeahead_model.dart
lib/widgets/widget/widget_model.dart
macos/Flutter/GeneratedPluginRegistrant.swift
web/workers/image_worker.dart.js

- Map marker bounds and from a static datasource did not rebuild.
- MAP MARKER
<details>
```xml
<FML color="white" layout="col" center="true">
<DATA id="trackerdata" root="locations.location">
<value>
<![CDATA[
<locations>
<location>
<place>first</place>
<coordinates>
<lat>-19.8</lat>
<lng>-5.8</lng>
</coordinates>
</location>
<location>
<place>second</place>
<coordinates>
<lat>-36.8</lat>
<lng>-157.8</lng>
</coordinates>
</location>
</locations>
]]>
</value>
</DATA>
<SELECT id="coordselect" data="trackerdata">
<OPTION value="{data.place}"/>
</SELECT>
<TXT value="lat: {coordselect.data.coordinates.lat}"/> …
```

Map fix static markers

---

.gitignore
lib/widgets/button/button_model.dart
macos/Flutter/GeneratedPluginRegistrant.swift

button fix merge conflict

---

lib/system.dart
lib/widgets/box/box_model.dart
lib/widgets/button/button_model.dart
lib/widgets/drawer/item/drawer_item_model.dart
lib/widgets/link/link_model.dart
lib/widgets/modal/modal_model.dart
lib/widgets/padding/padding_model.dart
lib/widgets/pager/pager_model.dart
lib/widgets/scroller/scroller_model.dart
lib/widgets/scroller/scroller_view.dart
lib/widgets/splitview/split_model.dart
lib/widgets/stack/stack_model.dart
lib/widgets/table/row/cell/table_row_cell_model.dart

- Scroller has issue shrinking
- SCROLL
<details>
```xml
```
</details>  

Scroll expand false fix

---

lib/system.dart
lib/widgets/animation/animation_child/size/size_transition_view.dart
lib/widgets/animation/animation_view.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.yaml

- SIZE now hugging children
- SIZE and any parent it is given
<details>
```xml
<ROW id="r1" halign="center" valign="center" color="red">
<TXT id="realtime" value="Real Time " bold="true" color="#5FC4FE" style="={layout} == 'column' ? 'h3' : 'h1'">
<ANIMATE duration="=length({realtime}) * 100" oncomplete="this.animate()" autoplay="true" ondismiss="this.animate()">
<SIZE begin="0.2" from="1" to="0" align="start"/>
</ANIMATE>
</TXT>
</ROW>
```
</details>  

Size transition constraint

---

lib/system.dart
lib/widgets/button/button_model.dart
lib/widgets/button/button_view.dart
lib/widgets/text/text_view.dart

Fixed Shadow
- Text Style for Button was same color as Background
- Shadow was truncated
- 
- 
- 
<BUTTON id="elevatedbtn" type="elevated" onclick="elevatedbtn.color.set('random');" radius="36" color="random">
Elevated Button
</BUTTON>

Fixed Default Text Color

---

lib/system.dart
lib/widgets/alarm/alarm_model.dart
lib/widgets/animation/animation_view.dart
lib/widgets/box/box_mixin.dart
lib/widgets/box/flex_renderer.dart
lib/widgets/scroller/scroller_model.dart
lib/widgets/text/text_view.dart

-   if the model wants to expand in the vertical/horizontal and has an unbounded
height/width, then set the min height/width to the parent height/width. This happens for
instance when a (box expand="true") is inside of a scroller. Normally the
expand would be set to false in the view. This ensures the widget is at least as
high/wide as the first parent with a constrained height/width.
- Expanding widgets inside a scroller are at least as big as the scroller
- SCROLLER
- As per test below
```xml
<FML layout="col">
<SCROLLER>
<BOX id="box1" center="true" expand="true" pad="40" color="green">
<ICON icon="save"/>
</BOX>
<BOX id="box2" center="true" expand="false" pad="40"  color="red">
</BOX>
</SCROLLER>
</FML>
```
Thank you for your effort to improve …

Layout mod scroller

---

lib/system.dart
lib/widgets/box/box_mixin.dart
lib/widgets/constraints/constraint_model.dart

- Added the ability to specify min/max width and height  by %
- Any variable sized widget can specify a min or max height
- All Viewable Widgets
- None
```xml
<FML layout="col">
<BOX color="green" minwidth="20%" minheight="20%" maxheigth="300"/>
</FML>
```

Min and Max Width/Height can now be expressed as a percentage

---

lib/widgets/list/item/list_item_model.dart
lib/widgets/popover/item/popover_item_model.dart
lib/widgets/popover/popover_model.dart
lib/widgets/popover/popover_view.dart

- Popover item scope was missing
- Added unqique scope for each item to allow binding
- POPOVER
- 

Fix for Popover

---

assets/applications/sample/templates/counter_app.xml
assets/applications/sample/templates/main.xml
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.yaml

fix packaged sample application

---

lib/system.dart
lib/widgets/framework/framework_view.dart
lib/widgets/treeview/tree_model.dart
lib/widgets/widget/widget_model.dart

- Safe Area calculation was incorrect
- No overflow on Mobile Keyboard Launch
- Framwork
- http://fml.dev

Modified Calc's for SafeArea

---

lib/widgets/animation/animation_model.dart
macos/Flutter/GeneratedPluginRegistrant.swift

- Fixed controllerValue on animation to non nullable double.
- ANIMATION and children
<details>
```xml
see fml.dev
```
</details>  

concrete type of double as controller

---

lib/system.dart
lib/widgets/html/html_view.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.yaml

- linux html view fix
- 
- Linux
- Can't perform until merged

update flutter html package for linux

---

lib/widgets/chart/chart_view.dart
macos/Flutter/GeneratedPluginRegistrant.swift

Prevent charts attempting to paint (and breaking build) when datasource is not provided
- Chart series bugfix when datasource is not provided
- 
- Series data= attribute
- 
<details>
```xml
<ROW>
<CHART id="testchart1" type="pie" showlegend="bottom">
<XAXIS type="category" title="Month" />
<YAXIS type="numeric" title="Amount" />
<SERIES name="Pie Series 1" type="pie" x="Monday" y="9" />
</CHART>
<CHART id="testchart2" type="pie" showlegend="bottom">
<XAXIS type="category" title="Month" />
<YAXIS type="numeric" title="Amount" />
<SERIES name="Pie Series 1" type="pie" data="DB1" x="{data.x2}" y="{data.y2}" …
```

chart missing datasource attribute warning and bug fix

---

lib/widgets/chart/chart_view.dart
lib/widgets/chart/series/chart_series_model.dart
macos/Flutter/GeneratedPluginRegistrant.swift

- Fixes the labels displaying on bar charts
- ~~Fixes the attribute on series labeled (bool) to allow for false and prevent labelling~~
- Removed the labeled attribute, setting label="" on the series will prevent labels without the need for an extra attribute
- Fixed Barchart Labels
- n/a
- Barchart series labels
- testing on windows desktop proper labels
<details>
```xml
<DATA id="DB2">
<VALUE>
<![CDATA[<SET>
<COORD>
<x1>January</x1> <y0>0</y0> <y1>50</y1> <y2>0</y2> <y3>0</y3> <y4>0</y4>	
</COORD>
<COORD>
<x1>February</x1> <y0>50</y0> <y1>0</y1> <y2>40</y2> <y3>0</y3> <y4>0</y4>
</COORD>
<COORD> …
```

chart series label fixes

---

lib/widgets/chart/chart_view.dart

patch to #416 
- 
- instead of the chart icon with loading indicator charts will build with axis while data loads
- 
-  

remove loading icon from chart without data

---

lib/widgets/button/button_model.dart
lib/widgets/text/text_model.dart
lib/widgets/text/text_view.dart

Fix text theme on button and fix text weight not being used as a stylization on text
- Button theming by button type
- Text weight stylization added
- weight can not be used on text
- button/text
- template incuded
<details>
```xml
<ROW wrap="true">
<BTN type="elevated" margin="10" label="A test button OK" onclick="open('resources/debug.xml');" />
<BTN type="outlined" margin="10" label="A test button OK" onclick="open('resources/debug.xml');" />
<BTN type="text" margin="10" label="A test button OK" onclick="open('resources/debug.xml');" />
<BTN type="elevated" margin="10" label="A test …
```

Fix button text

---

lib/widgets/box/flex/flex_renderer.dart
lib/widgets/chart/chart_model.dart
lib/widgets/chart/series/chart_series_model.dart
lib/widgets/list/list_model.dart
lib/widgets/list/list_view.dart
lib/widgets/map/map_model.dart
lib/widgets/map/map_view.dart
lib/widgets/treeview/tree_model.dart
lib/widgets/treeview/tree_view.dart
macos/Flutter/GeneratedPluginRegistrant.swift

- 
- 
- 
- 
<details>
```xml
```
</details>  

TreeView, MapView, ListView and ChartView are all now BoxViews

---

lib/widgets/chart/chart_view.dart
macos/Flutter/GeneratedPluginRegistrant.swift

prevents the pie chart labels from holding up other paint jobs
- Pie Chart label holding up other paints
- 
- Pie Charts
- 
<details>
```xml
<FML>
<COL>
<ROW visible="true">
<CHART showlegend="false">
<YAXIS type="numeric"/>
<XAXIS title="Departures" />
<SERIES name="Departure Day" data="distinctDepartureDay" type="pie" x="{data.departureDayOfWeek}" label="{data.departureDayOfWeek}" y="{data.departureCount}" />
</CHART>
<CHART showlegend="false">
<YAXIS type="numeric"/>
<XAXIS title="Arrivals" />
<SERIES name="Arrival Day" data="distinctArrivalDay" type="pie" x="{data.arrivalDayOfWeek}" …
```

pie chart label render paint freeze fix

---

lib/widgets/pager/pager_model.dart

- minor, made pager a slide transition by default, updated the docs and tested.

Pager slide

---

lib/widgets/button/button_model.dart

buttons should have even margin to match one another

even margin on buttons

---

lib/observable/observables/color.dart
macos/Flutter/GeneratedPluginRegistrant.swift

#aarrggbb is now #rrggbbaa to align with common practice
Color #aarrggbb is now #rrggbbaa to align with common practice, all other value types remain the same.
-  Color #aarrggbb is now #rrggbbaa to align with common practice, all other value types remain the same.
- color="" with a hex value is altered everywhere.
- color attribute when using a #aarrggbb will have to be converted
<details>
```xml
<ROW id="boxheight" layout="row" color="#7b008366" halign="between" pad="10"/>
<ROW id="boxheight" layout="row" color="#667b0083" halign="between" pad="10"/>
```
</details>  
Thank you for your effort to …

Fix for color hex

---

lib/widgets/editor/editor_view.dart
pubspec.yaml

Reduced the space code editor adds to margin and code size is now 14px
- fmlpad

code editor improvements

---

lib/eval/eval.dart
lib/helper/color.dart
lib/widgets/chart/chart_view.dart

- Added toEpoch() from DateTime String, returns an int
- Added isAfter() from 2 DateTime Strings, returns a bool
- Added isBefore() from 2 DateTime Strings, returns a bool
- Added timeBetween() 2 DateTime Strings, returns a datetime as a String
- Added addTime() that takes a String time amount (ie `1 day 2 hours`) and a DateTime String, returns a greater datetime as a String
- Added subtractTime() that takes a String time amount (ie `1 day 2 hours`) and a DateTime String, returns a lesser datetime as a String
- Added 6 DateTime eval functions (isAfter(), isBefore(), timebetween(), addTime(), subtractTime() and toEpoch())
- n/a
- Eval
- see test template
Paste a complete test template within the xml markdown and if applicable write here how to effectively reproduce your …

Add DateTime Eval Functions

---

lib/eval/eval.dart

Substring can now determine its start/end parameters from the end of the string as well as the start
- substring() eval now supports negative values for start and end to isolate based on the length of the string
- Deprecated the shortform substring() function that would act as substring(end) if given a negative, substring(start) still works acting as substring(start, string.length). TO achieve the old effect do substring(0, negative value);
- substring() eval
- See test template
<details>
```xml
<BTN type="elevated" margin="10" onclick="open('resources/debug.xml');" …
```

Improved substring

---

lib/widgets/chart/chart_view.dart
lib/widgets/image/image_view.dart
lib/widgets/modal/modal_view.dart

Fix for Pie chart preventing painting will null data

fix for pie chart

---

assets/applications/sample/templates/main.xml
lib/system.dart
lib/widgets/list/list_model.dart
macos/Flutter/GeneratedPluginRegistrant.swift

List would not rebuild when data was null coming back.
- List does not rebuild
<details>
```xml
See fmljet
```
</details>  

List null fix

---

lib/datasources/detectors/image/detectable_image.mobile.dart

Fixed the undocumented function changes to windows image detection from google
- Had to update some undocumented function changes after dep lib update
- n/a
- Windows
- Ran Windows

windows fixes for image detection lib updates

---

lib/observable/observables/list.dart
lib/widgets/list/list_model.dart
macos/Flutter/GeneratedPluginRegistrant.swift

- List was not rebinding when the data list returned as empty []
- Empty data sets will now clear previous bindings to the same data source
- LIST
- https://jet.fml.dev

Empty List was not changing list bindable.

---

lib/widgets/input/input_view.dart

Now using theme colorScheme
- fix lightmode input hint theme color

fix input hint color

---

lib/system.dart
lib/widgets/framework/framework_view.dart

Fixed appbar sizing not going down with scaffold
- Appbar no longer covers headers and framework
- Sizing
- FML
<details>
```xml
```
</details>  

Pad the scaffold to avoid top insets.

---

lib/widgets/framework/framework_view.dart

Added check for fw in fw
<details>
```xml
```
</details>  

Added check for fw in fw

---

ios/Podfile.lock
lib/system.dart
macos/Flutter/GeneratedPluginRegistrant.swift
macos/Podfile
macos/Podfile.lock
macos/Runner.xcodeproj/project.pbxproj
pubspec.yaml

Mac os compatibility with google packages

---

lib/helper/uri.dart
lib/system.dart

- Hash tag in a query string breaks the Uri.parse
- 
- 
- 
<details>
```xml
```
</details>  

Has tag in query parameter breaks URL parse.

---

lib/datasources/base/model.dart
lib/datasources/datasource_interface.dart
lib/datasources/file/file.web.dart
lib/datasources/socket/socket.dart
lib/dialog/alert.dart
lib/event/event.dart
lib/event/handler.dart
lib/helper/uri.dart
lib/page404/page404_view.dart
lib/widgets/box/box_view.dart
lib/widgets/filepicker/filepicker_web_view.dart
lib/widgets/form/form_model.dart
lib/widgets/framework/framework_model.dart
lib/widgets/grid/grid_model.dart
lib/widgets/grid/grid_view.dart
lib/widgets/list/item/list_item_model.dart
lib/widgets/splitview/split_view.dart
lib/widgets/table/row/table_row_model.dart
lib/widgets/table/table_model.dart
lib/widgets/table/table_view.dart
lib/widgets/tabview/tab_model.dart
lib/widgets/tabview/tab_view.dart
lib/widgets/widget/widget_model.dart

- Move export on grid and table from broadcast to excute()
- Fixed Web File Picker Read()
- 
- 
- 
<details>
```xml
```
</details>  

Moved export for Grid and Table to Execute(). Fixed File Picker on Web

---

lib/widgets/form/form_field_model.dart
lib/widgets/typeahead/typeahead_model.dart
lib/widgets/typeahead/typeahead_view.dart

- Fixed inputenabled
- inputenabled now works
- TYPEAHEAD 
<details>
```xml
<FML title="TABLE (example1)" linkable="true" layout="col">
<TYPEAHEAD id="i1" inputenabled="true">
<OPTION value="yes"/>
<OPTION value="no" label="ohno"/>
</TYPEAHEAD>
<TEXT value="VAL: {i1}"/>
</FML>
```
</details>  

Typeahead input fix

---

lib/widgets/datepicker/datepicker_model.dart

- Fixed format getting reset
- all dates including input, output, oldest, and newest, will follow the format.
- DATEPICKER
<details>
```xml
<DATEPICKER id="dt1" type="datetime" format="yyyy-MM-dd hh:mm" newest="{SYSTEM.year}-{SYSTEM.month}-{SYSTEM.day} 00:00"/>
```
</details>  

Fix datepicker format

---

lib/helper/uri.dart
lib/navigation/navigation_manager.dart
lib/store/store_view.dart
lib/widgets/chart/chart_view.dart
lib/widgets/chart_syncfusion/chart_view.dart
lib/widgets/form/form_view.dart
lib/widgets/framework/framework_model.dart
lib/widgets/framework/framework_view.dart
lib/widgets/googlemap/map_view.dart
lib/widgets/grid/grid_view.dart
lib/widgets/list/list_view.dart
lib/widgets/map/map_view.dart
lib/widgets/menu/menu_view.dart
lib/widgets/pager/pager_view.dart
lib/widgets/select/select_view.dart
lib/widgets/table/table_view.dart
lib/widgets/tabview/tab_view.dart
lib/widgets/widget/widget_model.dart
test/widgets/busy/busy_test.dart

Removed jank to double busy spinner and added some refactoring
- Removed jank to double busy spinner and added some refactoring
- 
- Navigation and page load
- 
<details>
```xml
```
</details>  

Busy spinner remove jank

---

lib/widgets/form/decorated_input_model.dart

Fixed the color and width of input, allow input to expand width wise.
- Fix color when border is al on input. Allow input to be expandable like the other widgets.
- input will now expand and use % 
- INPUT
- 
<details>
```xml
```
</details>  

Input change

---

lib/widgets/framework/framework_view.dart

onstart timing was off due to initialised and started being used seperately.
- 
- 
- 
- 
<details>
```xml
```
</details>  

small fix for onstart

---

lib/helper/xml.dart

Case sensitivity universal.
- Reordered the toupper and to lower to become more case sensitive and not preform unneccesary actions.

reorder the touppers, potentially remove?

---

lib/widgets/form/decorated_input_model.dart

Input color was removed
<details>
```xml
```
</details>  

fixed input decoration

---

lib/system.dart
lib/widgets/grid/grid_view.dart
lib/widgets/list/list_view.dart
lib/widgets/table/table_view.dart

- Null safe flutter forced us to switch from Listview.builder to Listview.custom. This is now fixed in latest flutter release
- 
- 
- 
<details>
```xml
```
</details>  

Newest release of flutter allows us to switch back to Listview.builder

---

lib/eval/eval.dart
lib/system.dart

Reversed the loop when replacing string call expressions
- [**Bug Fix**]]
<details>
```xml
<FML>
<VAR id="a1" value="{a}"/>
<VAR id="b1" value="{b}"/>
<VAR id="c1" value="{c}"/>
<VAR id="d1" value="{d}"/>
<VAR id="e1" value="{e}"/>
<VAR id="f1" value="{f}"/>
<VAR id="g1" value="{g}"/>
<VAR id="h1" value="{h}"/>
<VAR id="i1" value="{i}"/>
<VAR id="j1" value="{j}"/>
<VAR id="k1" value="{k}"/>
<VAR id="l1" value="{l}"/>
<VAR id="m1" value="{m}"/>
<VAR id="n1" value="{n}"/>
<VAR id="o1" value="{0}"/>
<BTN onclick="open('/resources/isaactest3.xml?a={a1}&amp;b={b1}&amp;c={c1}&amp;d={d1}&amp;e={e1}&amp;f={f1}&amp;g={g1}&amp;h={h …
```

fix for the replaceall loop replacing ___v10 with ____v1

---

lib/system.dart
lib/widgets/checkbox/checkbox_view.dart
lib/widgets/input/input_view.dart
lib/widgets/tabview/tab_view.dart

Fixed input not updating with eval, updated checkboxes, display file not url in tabview
<details>
```xml
<FML layout="col">
<CHECK id="c1">
<OPTION value="yes"/>
<OPTION value="no"/>
</CHECK>
<INPUT id="i1" value="{c1}"/>
<TEXT value="{i1}"></TEXT>
</FML>
```
</details>  

Input value fix

---

lib/widgets/input/input_view.dart

<details>
```xml
```
</details>  

seperated onmodelchange into two statements

---

lib/widgets/table/row/table_row_view.dart

Patch bug introduced
<details>
```xml
```
</details>  

Fix table row view

---

lib/widgets/drawer/drawer_view.dart
lib/widgets/framework/framework_view.dart
lib/widgets/input/input_view.dart
lib/widgets/table/table_model.dart
lib/widgets/table/table_view.dart

FRAMEWORK - Drawer Bug on Table Display
- Drawer was double wrapping gestures and stack and Table would not display first row on load.
- INPUT editable="false" was defeated
- 
- 
- 
<details>
```xml
```
</details>  

INPUT editable="false" fix

---

lib/eval/eval.dart
lib/widgets/box/box_model.dart
lib/widgets/table/table_model.dart
lib/widgets/table/table_row_cell_model.dart

Extended the case statement to take a List [] or key, value, key, value or 2 lists [key,key,key] and [value, value, value]
case now allows list to be passed as 2nd and 3rd parameters
- case(value, [value1, key2, value2, ...., keyN, valueN]);
- case(value, [value1, value2, ... valueN], [key1, key2, ... keyN]);
- 
- 
- 
<details>
```xml
```
</details>  

Minor Table Fixes

---

web/index.html

- Modified INDFEX.html to support non-caching on subsequent builds
- NOTE: Find and change
createScriptURL(k+j+e)  change to => createScriptURL(k+j+e+`?v=${serviceWorkerVersion}`) 
in main.dart.js after release build and before deployment
also note, createScriptURL(k+j+e) variables may be different letters (not k+j+e) in minified version of main.dart.js
- 
- 
- 
<details>
```xml
```
</details>  

Added meta tag in index.html to fix cache issue

---

lib/eval/eval.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

Eval Case Fix

---

lib/eval/eval.dart
lib/system.dart
lib/widgets/iframe/inline_frame_model.dart
lib/widgets/iframe/inline_frame_web_view.dart
lib/widgets/modal/modal_model.dart
lib/widgets/modal/modal_view.dart
lib/widgets/widget/widget_model.dart

- iFRAMES did not allow the user to change the URL
- 
- 
- 
<details>
```xml
```
</details>  

iFrame mods

---

lib/eval/eval.dart

- add an abs() function to eval
- 
- 
- 
<details>
```xml
```
</details>  

Added Abs() function to eval

---

lib/widgets/viewable/viewable_widget_model.dart

- You can now add tip="xxx" attribute on viewable widgets where you only require plain text and not complex FML widgets
- 
- 
- 
<details>
```xml
```
</details>  

Added tooltip shortcut using tip="xxxx" attribute for plain text.

---

lib/system.dart
lib/widgets/table/table_view.dart

- TABLE row alternating colors was broken
- 
- 
- 
<details>
```xml
```
</details>  

Alernating row colors

---

android/app/src/main/kotlin/co/appdaddy/fml/MainActivity.kt
lib/datasources/base/model.dart
lib/datasources/nfc/nfc.dart
lib/datasources/nfc/nfc_model.dart
lib/models/custom_exception.dart
lib/observable/binding.dart
lib/observable/scope.dart
lib/observable/scope_manager.dart
lib/system.dart
lib/widgets/box/box_model.dart
lib/widgets/checkbox/checkbox_model.dart
lib/widgets/form/form_model.dart
lib/widgets/form/form_view.dart
lib/widgets/grid/grid_model.dart
lib/widgets/list/list_model.dart
lib/widgets/menu/menu_model.dart
lib/widgets/pager/pager_model.dart
lib/widgets/popover/popover_model.dart
lib/widgets/radio/radio_model.dart
lib/widgets/scope/scope_model.dart
lib/widgets/scope/scope_view.dart
lib/widgets/select/select_model.dart
lib/widgets/table/table_model.dart
lib/widgets/treeview/tree_model.dart
lib/widgets/typeahead/typeahead_model.dart
lib/widgets/viewable/viewable_widget_model.dart
lib/widgets/widget/widget_model.dart

- Any visual element with a datasource and a single child is considered a prototype
- 
- 
- 
<details>
```xml
```
</details>  

Generic Prototypes

---

lib/system.dart
lib/widgets/input/input_view.dart
lib/widgets/table/table_header_cell_model.dart
lib/widgets/table/table_model.dart
lib/widgets/table/table_row_cell_model.dart
lib/widgets/table/table_view.dart
pubspec.yaml

- 
- 
- 
- 
<details>
```xml
```
</details>  

Table fixes for prototype

---

lib/system.dart
lib/widgets/input/input_view.dart
pubspec.yaml

Fix input padding

---

android/app/src/main/kotlin/co/appdaddy/fml/DWInterface.kt
android/app/src/main/kotlin/co/appdaddy/fml/MainActivity.kt
android/app/src/main/kotlin/co/appdaddy/fml/Scan.kt
lib/datasources/detectors/barcode/barcode_detector.dart
lib/datasources/zebra/model.dart
lib/datasources/zebra/wedge.dart
lib/observable/observable.dart
lib/system.dart
lib/widgets/chart_painter/zoom_chart.dart
lib/widgets/form/form_model.dart
lib/widgets/table/table_view.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

Data wedge rfid 2

---

lib/observable/binding.dart
lib/system.dart
lib/widgets/table/table_header_cell_model.dart

Scoped bindings have format <scopeId>@<sourceId>.<propertyId>.<propertyId> ...
- 
- 
- 
- 
<details>
```xml
```
</details>  

Modified code to support named binding reference

---

lib/observable/binding.dart
lib/system.dart
lib/widgets/table/table_model.dart
lib/widgets/widget/widget_model.dart

reverted earlier change
- 
- 
- 
- 
<details>
```xml
```
</details>  

Modified code to support prototype code

---

lib/widgets/form/form_field_interface.dart
lib/widgets/form/form_field_model.dart
lib/widgets/form/form_interface.dart
lib/widgets/form/form_model.dart
lib/widgets/list/item/list_item_model.dart
lib/widgets/list/list_model.dart
lib/widgets/table/table_model.dart
lib/widgets/table/table_row_model.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

Updates to Form Logic to support Table

---

lib/system.dart
lib/widgets/checkbox/checkbox_model.dart
lib/widgets/datepicker/datepicker_model.dart
lib/widgets/field/field_model.dart
lib/widgets/form/form_model.dart
lib/widgets/input/input_model.dart
lib/widgets/radio/radio_model.dart
lib/widgets/select/select_model.dart
lib/widgets/select/select_view.dart
lib/widgets/slider/slider_model.dart
lib/widgets/typeahead/typeahead_model.dart
lib/widgets/viewable/viewable_widget_model.dart

filling of fields bound to data. The defaultValue setting was also modified
- 
- 
- 
- 
<details>
```xml
```
</details>  

Modfied select, radio and typeahead to support

---

lib/widgets/form/form_model.dart
lib/widgets/viewable/viewable_widget_model.dart
lib/widgets/widget/widget_model.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

Bug Fix in Fill Empty Fields

---

lib/data/data.dart
lib/datasources/base/model.dart
lib/eval/eval.dart
lib/helper/xml.dart
lib/system.dart
lib/widgets/box/box_model.dart
lib/widgets/checkbox/checkbox_model.dart
lib/widgets/column/column_model.dart
lib/widgets/form/form_model.dart
lib/widgets/grid/grid_model.dart
lib/widgets/list/item/list_item_model.dart
lib/widgets/list/list_model.dart
lib/widgets/menu/menu_model.dart
lib/widgets/pager/pager_model.dart
lib/widgets/popover/popover_model.dart
lib/widgets/prototype/prototype_model.dart
lib/widgets/radio/radio_model.dart
lib/widgets/row/row_model.dart
lib/widgets/select/select_model.dart
lib/widgets/table/table_model.dart
lib/widgets/table/table_row_model.dart
lib/widgets/treeview/tree_model.dart
lib/widgets/typeahead/typeahead_model.dart
lib/widgets/viewable/viewable_widget_model.dart
lib/widgets/widget/widget_model.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

Updates to ProtoType

---

lib/eval/eval.dart
lib/eval/evaluator.dart
lib/eval/parser.dart
lib/event/handler.dart
lib/system.dart

- allow <var> = <value> rather than having to use <var>.set(<value>)
- 
- 
- 
<details>
```xml
```
</details>  

Eval parser changes

---

lib/datasources/base/model.dart
lib/eval/eval.dart
lib/event/handler.dart
lib/helper/string.dart
lib/main.dart
lib/observable/observable.dart
lib/observable/observables/string.dart
lib/system.dart
lib/widgets/widget/widget_model.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

Datasource Body Formatting

---

lib/system.dart
lib/widgets/form/form_model.dart
macos/Flutter/GeneratedPluginRegistrant.swift
windows/flutter/generated_plugins.cmake

Form is dirty when a subelement is a prototype
Form is still dirty once complete() fires when the new prototype fields are present.

Temporary fix to dirty

---

lib/data/data.dart
lib/eval/eval.dart
lib/helpers/json.dart
macos/Flutter/GeneratedPluginRegistrant.swift
windows/flutter/generated_plugins.cmake

- 
- 
- 
- 
<details>
```xml
```
</details>  

Modfied to Json to Xml Eval routine

---

lib/datasources/base/model.dart
lib/datasources/datasource_interface.dart
lib/event/handler.dart
lib/helpers/template.dart
lib/hive/data.dart
lib/widgets/dragdrop/droppable_view.dart
lib/widgets/table/table_model.dart
lib/widgets/table/table_view.dart
lib/widgets/viewable/viewable_widget_model.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

Local remote data binding

---

lib/datasources/base/model.dart
lib/event/handler.dart
lib/widgets/dragdrop/drag_drop_interface.dart
lib/widgets/dragdrop/dragdrop.dart
lib/widgets/dragdrop/draggable_view.dart
lib/widgets/dragdrop/droppable_view.dart
lib/widgets/list/item/list_item_model.dart
lib/widgets/list/list_model.dart
lib/widgets/list/list_view.dart
lib/widgets/table/table_model.dart
lib/widgets/viewable/viewable_widget_model.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

Added functionality to allow list and table drag drop

---

lib/widgets/dragdrop/drag_drop_interface.dart
lib/widgets/dragdrop/dragdrop.dart
lib/widgets/dragdrop/droppable_view.dart
lib/widgets/grid/grid_model.dart
lib/widgets/grid/grid_view.dart
lib/widgets/grid/item/grid_item_model.dart
lib/widgets/list/item/list_item_model.dart
lib/widgets/list/list_model.dart
lib/widgets/menu/item/menu_item_model.dart
lib/widgets/menu/menu_model.dart
lib/widgets/menu/menu_view.dart
lib/widgets/prototype/prototype_model.dart
lib/widgets/viewable/viewable_widget_model.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

List drag drop

---

lib/widgets/prototype/prototype_model.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

Prototype fix

---

lib/datasources/base/model.dart
lib/helpers/map.dart
lib/observable/scope.dart
lib/widgets/grid/grid_model.dart
lib/widgets/list/list_model.dart
lib/widgets/table/table_model.dart
lib/widgets/table/table_view.dart
lib/widgets/viewable/viewable_widget_model.dart
lib/widgets/widget/widget_model.dart

Refactoring and ReOrg of some files
- 
- 
- 
- 
<details>
```xml
```
</details>  

Drag and Drop Modifications

---

lib/widgets/typeahead/typeahead_model.dart

clearOptions was referenced by accident.
- 
- 
- 
- 
<details>
```xml
```
</details>  

function not being called

---

lib/observable/observable.dart
lib/system.dart
lib/widgets/form/form_model.dart
lib/widgets/icon/icon_model.dart
lib/widgets/icon/icon_view.dart
lib/widgets/image/image_model.dart
lib/widgets/image/image_view.dart
lib/widgets/list/item/list_item_model.dart
lib/widgets/list/list_model.dart
lib/widgets/positioned/positioned_model.dart
lib/widgets/table/table_model.dart
lib/widgets/viewable/viewable_widget_model.dart

- Added rotation="number" to all viewable widgets
- 
- 
- 
<details>
```xml
```
</details>  

Add rotation="number" to all viewable widgets

---

lib/widgets/table/table_view.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

Fix yable update issue

---

lib/widgets/icon/icon_view.dart
lib/widgets/table/table_footer_cell_model.dart
lib/widgets/table/table_header_cell_model.dart
lib/widgets/table/table_header_model.dart
lib/widgets/table/table_model.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

Mods to dynamic table building

---

lib/application/application_model.dart
lib/template/template.dart
lib/widgets/framework/framework_model.dart
web/config.xml

- 
- 
- 
- 
<details>
```xml
```
</details>  

Added custom error page if defined in config.xml <ERROR_PAGE/>

---

lib/datasources/transforms/pivot.dart
lib/system.dart
lib/widgets/box/box_model.dart
lib/widgets/box/box_view.dart
lib/widgets/table/table_row_model.dart
web/config.xml

- 
- 
- 
- 
<details>
```xml
```
</details>  

Fixed Pivot table

---

lib/eval/eval.dart
lib/system.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

Eval split

---

lib/eval/eval.dart
lib/system.dart
lib/widgets/form/form_field_model.dart
lib/widgets/input/input_view.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

Fix to Eval Complete

---

lib/system.dart
lib/widgets/card/card_model.dart
lib/widgets/table/table_model.dart

- Dynamically built row cells were lost when no data was returned
- 
- 
- 
<details>
```xml
```
</details>  

Dynamic table row cell bug fix

---

lib/widgets/video/video_model.dart
lib/widgets/video/video_view.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.yaml

- 
- 
- 
- 
<details>
```xml
```
</details>  

fixed bug on video player

---

lib/helpers/template.dart
lib/helpers/xml.dart
macos/Flutter/GeneratedPluginRegistrant.swift
windows/flutter/generated_plugins.cmake

- We updated case on elements, they must always be uppercase in order for attributes as elements to work
- 
- 
- 
<details>
```xml
```
</details>  

Case sensitive

---

lib/dialog/alert.dart
lib/dialog/manager.dart
lib/event/handler.dart
lib/widgets/video/video_model.dart
lib/widgets/video/video_view.dart

alert('my message') now supported. you can pass any/all parameters
- 
- 
- 
<details>
```xml
```
</details>  

Alerts-Mods

---

lib/helpers/xml.dart
lib/widgets/table/table_model.dart
lib/widgets/table/table_row_model.dart
lib/widgets/video/video_model.dart
lib/widgets/viewable/viewable_widget_model.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

attributes are lower and elements are upper

---

lib/sound/sound.dart
lib/system.dart
lib/widgets/map/map_view.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.yaml
windows/flutter/generated_plugins.cmake

- 
- 
- 
- 
<details>
```xml
```
</details>  

Updated packages and dependencies

---

lib/widgets/widget/widget_model.dart
macos/Flutter/GeneratedPluginRegistrant.swift
windows/flutter/generated_plugins.cmake

Fixed bug for data attribute to lowercase
- 
- 
- 
- 
<details>
```xml
```
</details>  

Fix xml get attribute should be get

---

android/build.gradle
lib/system.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.yaml
windows/flutter/generated_plugins.cmake

cross_connectivity has been removed as it wasnt kept up to date with the newest package.
- 
- 
- 
- 
<details>
```xml
```
</details>  

update kotlin gradle & removed cross connectivity

---

lib/connectivity/connectivity.dart
lib/connectivity/connectivity.mobile.dart
lib/connectivity/connectivity.web.dart
lib/eval/eval.dart
lib/system.dart
pubspec.yaml
windows/flutter/generated_plugins.cmake

- 
- 
- 
- 
<details>
```xml
```
</details>  

Connectivity fix

---

lib/system.dart
lib/template/template_manager.dart
lib/widgets/table/table_view.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

Bug in page transitions

---

lib/eval/eval.dart
lib/system.dart
lib/widgets/form/form_field_model.dart
lib/widgets/input/input_view.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

Input alarm fix2

---

lib/helpers/template.dart
lib/helpers/xml.dart
lib/system.dart
lib/widgets/checkbox/checkbox_model.dart
lib/widgets/checkbox/checkbox_view.dart
lib/widgets/datepicker/datepicker_model.dart
lib/widgets/datepicker/datepicker_view.dart
lib/widgets/form/decorated_input_model.dart
lib/widgets/form/form_field_model.dart
lib/widgets/icon/icon_view.dart
lib/widgets/input/input_model.dart
lib/widgets/input/input_view.dart
lib/widgets/option/option_model.dart
lib/widgets/option/tag_model.dart
lib/widgets/radio/radio_model.dart
lib/widgets/radio/radio_view.dart
lib/widgets/select/select_model.dart
lib/widgets/select/select_view.dart
lib/widgets/typeahead/typeahead_model.dart
lib/widgets/typeahead/typeahead_view.dart
lib/widgets/viewable/viewable_widget_model.dart
pubspec.yaml

- Modified TYPEAHEAD - added new <TAG/> element for searching
- Modified SELECT
- Modified CHECKBOX
- Modified RADIO
- 
- 
- 
<details>
```xml
```
</details>  

Typeahead mods

---

lib/widgets/typeahead/typeahead_model.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

checkbox and radio

---

lib/helpers/template.dart
lib/phrase.dart
lib/widgets/nodata/nomatch_model.dart
lib/widgets/select/select_model.dart
lib/widgets/select/select_view.dart
lib/widgets/table/table_model.dart
lib/widgets/typeahead/typeahead_model.dart
lib/widgets/typeahead/typeahead_view.dart
lib/widgets/viewable/viewable_widget_model.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

Nomatch nodata widgets

---

lib/helpers/template.dart
lib/system.dart
lib/widgets/form/form_model.dart
lib/widgets/framework/framework_model.dart
lib/widgets/framework/framework_view.dart
lib/widgets/prototype/prototype_model.dart
lib/widgets/widget/widget_model.dart

Found several bugs that were part of the change to upper/lower case widgets
- 
- 
- 
- 
<details>
```xml
```
</details>  

Widget model mods

---

lib/application/application_manager.dart
lib/platform/platform.web.dart
lib/system.dart
lib/theme/themenotifier.dart
lib/widgets/framework/framework_model.dart
lib/widgets/treeview/tree_model.dart
lib/widgets/widget/widget_model.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

Code clean up

---

lib/helpers/template.dart
lib/system.dart
lib/theme/themenotifier.dart
lib/widgets/colorpicker/colorpicker_model.dart
lib/widgets/colorpicker/colorpicker_view.dart
pubspec.yaml

-  Added simple <COLORPICKER/>
- 
- 
- 
<details>
```xml
```
</details>  

Color picker

---

pubspec.yaml

- Downgrades google_fonts dependency to 6.1.0 instead of ^6.1.0, which is a breaking change
- None.
- None.
- Built FML with modified pubspec.yaml file
Fixes #560

Downgrade google_fonts to fix build

---

lib/widgets/widget/widget_model.dart

- 
- 
- 
- 
<details>
```xml
```
</details>  

Merge conflict fix

---

lib/application/application_model.dart
lib/widgets/button/button_model.dart
lib/widgets/dragdrop/droppable_view.dart
lib/widgets/filepicker/filepicker_model.dart
lib/widgets/icon/icon_model.dart
lib/widgets/text/text_view.dart

- Package update mods
- Can now use value="" in place of icon="" from <ICON/>
- 
- 
- 
<details>
```xml
```
</details>  

General fixes package updates

---

lib/data/data.dart
lib/eval/eval.dart
lib/eval/evaluator.dart
lib/eval/expressions.dart
lib/eval/parser.dart
lib/widgets/viewable/viewable_widget_mixin.dart

-fixed bug with fractional Rationals
added functions:
lpad(v,length,char)
rpad(v,length,char)
toint(v)
todouble(v)

modified eval()

---

lib/widgets/table/table_view.dart
lib/widgets/viewable/viewable_view.dart

Layout mods had typo causing issues with header and row builds (inflate())

Table want rebuilding on Theme change

---

lib/widgets/box/box_model.dart
lib/widgets/box/box_view.dart
lib/widgets/button/button_model.dart
lib/widgets/button/button_view.dart
lib/widgets/datepicker/datepicker_model.dart
lib/widgets/datepicker/datepicker_view.dart
lib/widgets/form/decorated_input_model.dart
lib/widgets/input/input_model.dart
lib/widgets/input/input_view.dart
lib/widgets/positioned/positioned_model.dart
lib/widgets/positioned/positioned_view.dart
lib/widgets/select/select_view.dart
lib/widgets/typeahead/typeahead_view.dart

Cleaned up deserialization on decorated input

Updates to elevated button text style (was not showing proper color)

---

lib/widgets/box/box_model.dart
lib/widgets/box/box_view.dart
lib/widgets/colorpicker/colorpicker_model.dart
lib/widgets/colorpicker/colorpicker_view.dart
lib/widgets/datepicker/datepicker_view.dart
lib/widgets/table/table_footer_model.dart
lib/widgets/table/table_model.dart

Modified Box - Corner Radius Fix

---

example/lib/main.dart
lib/datasources/mqtt/mqtt.web.dart
lib/datasources/socket/socket.dart
lib/helpers/color.dart
lib/widgets/video/video_view.dart

Video player mods

---

example/lib/main.dart
lib/datasources/base/model.dart
lib/widgets/checkbox/checkbox_model.dart

Checkbox set was not setting the options checkmark

Fix for setting checkbox value

---

lib/widgets/checkbox/checkbox_model.dart

Checkbox mods

---

example/lib/main.dart
lib/navigation/navigation_observer.dart
lib/widgets/input/input_view.dart

Editable was not working on INPUT

editable=false was not working on input

---

example/lib/main.dart
lib/widgets/grid/item/grid_item_model.dart
lib/widgets/list/item/list_item_model.dart
lib/widgets/table/table_row_model.dart
lib/widgets/viewable/viewable_model.dart

Table wasnt being marked as dirty

Table was not being set dirty

---

lib/widgets/input/input_view.dart

Added "selectonfocus" attribute

Fixed issue with disappearing text

---

example/lib/main.dart
lib/data/data.dart
lib/datasources/transforms/pivot.dart
lib/datasources/transforms/sort.dart
lib/eval/eval.dart
lib/widgets/grid/grid_model.dart
lib/widgets/list/list_model.dart
lib/widgets/menu/menu_model.dart
lib/widgets/prototype/prototype_model.dart
lib/widgets/table/table_footer_cell_model.dart
lib/widgets/table/table_footer_model.dart
lib/widgets/table/table_header_cell_model.dart
lib/widgets/table/table_header_model.dart
lib/widgets/table/table_model.dart
lib/widgets/table/table_view.dart
lib/widgets/widget/model.dart

Added header and footer summary data (min,max,sum,count,avg) Added iform field for posting table rows via complete for simple tables that use the inline editing

Modified pivot transform to include/exclude summary rows.

---

lib/eval/eval.dart
lib/widgets/form/form_model.dart

added encode and decode to eval. Encode encodes a string to base64 by default and decode from base64 to string

added method submit() to <FORM/> as an alias for complete()

---

lib/datasources/transforms/pivot.dart

When set to true, avg and total appear at the right end of the data set.  Defaults to false, meaning avg and total are not added to the dataset.

Added addsummarycolumns toggle

---

lib/datasources/base/model.dart
lib/datasources/zebra/zebra_model.dart
lib/store/store_model.dart

Removed some unused libraries

---

example/lib/main.dart
lib/datasources/base/model.dart
lib/datasources/zebra/zebra_model.dart
pubspec.yaml

Fixed datasource.clear() methid call. Wast notifying listeners.

Updated <ZEBRA/> to 2.0.1 of the plugin.

---

example/android/gradle/wrapper/gradle-wrapper.properties
ios/Flutter/Generated.xcconfig
ios/Flutter/flutter_export_environment.sh
lib/datasources/base/model.dart

https://docs.flutter.dev/release/breaking-changes/layout-builder-optimization

layoutBuilder issues in release

---

lib/widgets/box/box_model.dart
lib/widgets/button/button_model.dart
lib/widgets/prototype/prototype_model.dart
lib/widgets/scroller/scroller_model.dart

prototype layout is the prototypes parent not the prototype layout itself.

scroller layout changes did not change scroller layout.

---

example/lib/main.dart
lib/observable/binding.dart
lib/widgets/input/input_model.dart

Added clear() to input.

---

example/lib/main.dart
lib/widgets/map/map_model.dart
lib/widgets/map/map_view.dart
lib/widgets/map/marker/map_marker_model.dart

Added boolean observable "fit" to automatically bound all markers

Map Markers not tied to a data source did not adjust the map on change.
